version: '2.1'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - 'db'
    ports:
      - 8088:8088
    volumes:
      - /opt/Docker-compose/sample
      - .:/opt/Docker-compose/project 
    depends_on:
      db:
          condition: service_healthy


  db:
    image: mariadb
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Test_123
      MYSQL_DATABASE: mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "172.31.31.129"]
      timeout: 20s
      retries: 10
    
